((!DOCTYPE ((html)))
 (html ((lang . "en"))
   (head ()
     (meta ((charset . "UTF-8")))
     (!-- () "Copyright (c) 2019 Michael Erickson\nYay")
     (title () "OOFF Test")
     (link ((rel . "stylesheet") (href . "test.css"))))
   (body ()
     (header ()
       (nav ()
         (ul ()
           (li () (! () (a ((href . "/")) "michae2.xyz")))
           (li () (! () (a ((href . "/blog/")) "blog")))
           (li () "test"))))
     (main ()
       (article ()
         (header ()
           (h1 () (! () (b () "OOFF") " Test")))
         (section ()
           (h2 ())
           (p () (! () (b () "Four score and seven years ago") "our fathers\n"
                       "brought forth on this continent, a new nation,\n"
                       "conceived in Liberty, and dedicated to the\n"
                       "proposition that all men are created equal.")))
         (section ()
           (h2 ())
           (p ()))
         (canvas ())))
     (footer ()))))
